name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create report file
        run: date +%s > report.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: FenGsHt
          author_email: 478901704@qq.com
          message: 'workflow'
          add: 'report.txt'